// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: event/v1/event.proto

package eventpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeliveryMode determines how messages are distributed to subscribers.
type DeliveryMode int32

const (
	DeliveryMode_DELIVERY_MODE_UNSPECIFIED DeliveryMode = 0
	DeliveryMode_DELIVERY_MODE_BROADCAST   DeliveryMode = 1
	DeliveryMode_DELIVERY_MODE_WORKER_POOL DeliveryMode = 2
)

// Enum value maps for DeliveryMode.
var (
	DeliveryMode_name = map[int32]string{
		0: "DELIVERY_MODE_UNSPECIFIED",
		1: "DELIVERY_MODE_BROADCAST",
		2: "DELIVERY_MODE_WORKER_POOL",
	}
	DeliveryMode_value = map[string]int32{
		"DELIVERY_MODE_UNSPECIFIED": 0,
		"DELIVERY_MODE_BROADCAST":   1,
		"DELIVERY_MODE_WORKER_POOL": 2,
	}
)

func (x DeliveryMode) Enum() *DeliveryMode {
	p := new(DeliveryMode)
	*p = x
	return p
}

func (x DeliveryMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryMode) Descriptor() protoreflect.EnumDescriptor {
	return file_event_v1_event_proto_enumTypes[0].Descriptor()
}

func (DeliveryMode) Type() protoreflect.EnumType {
	return &file_event_v1_event_proto_enumTypes[0]
}

func (x DeliveryMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryMode.Descriptor instead.
func (DeliveryMode) EnumDescriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{0}
}

// StartPosition determines where to start reading messages from.
type StartPosition int32

const (
	StartPosition_START_POSITION_UNSPECIFIED StartPosition = 0
	StartPosition_START_POSITION_BEGINNING   StartPosition = 1
	StartPosition_START_POSITION_LATEST      StartPosition = 2
	StartPosition_START_POSITION_TIMESTAMP   StartPosition = 3
)

// Enum value maps for StartPosition.
var (
	StartPosition_name = map[int32]string{
		0: "START_POSITION_UNSPECIFIED",
		1: "START_POSITION_BEGINNING",
		2: "START_POSITION_LATEST",
		3: "START_POSITION_TIMESTAMP",
	}
	StartPosition_value = map[string]int32{
		"START_POSITION_UNSPECIFIED": 0,
		"START_POSITION_BEGINNING":   1,
		"START_POSITION_LATEST":      2,
		"START_POSITION_TIMESTAMP":   3,
	}
)

func (x StartPosition) Enum() *StartPosition {
	p := new(StartPosition)
	*p = x
	return p
}

func (x StartPosition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StartPosition) Descriptor() protoreflect.EnumDescriptor {
	return file_event_v1_event_proto_enumTypes[1].Descriptor()
}

func (StartPosition) Type() protoreflect.EnumType {
	return &file_event_v1_event_proto_enumTypes[1]
}

func (x StartPosition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StartPosition.Descriptor instead.
func (StartPosition) EnumDescriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{1}
}

// HealthStatus represents the health state of the server.
type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_DEGRADED    HealthStatus = 2
	HealthStatus_HEALTH_STATUS_UNHEALTHY   HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_DEGRADED",
		3: "HEALTH_STATUS_UNHEALTHY",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_DEGRADED":    2,
		"HEALTH_STATUS_UNHEALTHY":   3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_event_v1_event_proto_enumTypes[2].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_event_v1_event_proto_enumTypes[2]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{2}
}

// RegisterEventRequest is the request for RegisterEvent.
type RegisterEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterEventRequest) Reset() {
	*x = RegisterEventRequest{}
	mi := &file_event_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEventRequest) ProtoMessage() {}

func (x *RegisterEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEventRequest.ProtoReflect.Descriptor instead.
func (*RegisterEventRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// RegisterEventResponse is the response for RegisterEvent.
type RegisterEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterEventResponse) Reset() {
	*x = RegisterEventResponse{}
	mi := &file_event_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEventResponse) ProtoMessage() {}

func (x *RegisterEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEventResponse.ProtoReflect.Descriptor instead.
func (*RegisterEventResponse) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{1}
}

// UnregisterEventRequest is the request for UnregisterEvent.
type UnregisterEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterEventRequest) Reset() {
	*x = UnregisterEventRequest{}
	mi := &file_event_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterEventRequest) ProtoMessage() {}

func (x *UnregisterEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterEventRequest.ProtoReflect.Descriptor instead.
func (*UnregisterEventRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *UnregisterEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// UnregisterEventResponse is the response for UnregisterEvent.
type UnregisterEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterEventResponse) Reset() {
	*x = UnregisterEventResponse{}
	mi := &file_event_v1_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterEventResponse) ProtoMessage() {}

func (x *UnregisterEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterEventResponse.ProtoReflect.Descriptor instead.
func (*UnregisterEventResponse) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{3}
}

// ListEventsRequest is the request for ListEvents.
type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_event_v1_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{4}
}

// ListEventsResponse is the response for ListEvents.
type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []string               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_event_v1_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{5}
}

func (x *ListEventsResponse) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

// PublishRequest is the request for Publish.
type PublishRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event name to publish to.
	Event string `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// Optional message ID. If empty, the server generates one.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Message payload as bytes.
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Optional key-value metadata.
	Metadata      map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_event_v1_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{6}
}

func (x *PublishRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *PublishRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublishRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PublishRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// PublishResponse is the response for Publish.
type PublishResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The message ID (generated if not provided).
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_event_v1_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{7}
}

func (x *PublishResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// SubscribeRequest is the request for Subscribe.
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event name to subscribe to.
	Event string `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// Delivery mode (broadcast or worker pool).
	DeliveryMode DeliveryMode `protobuf:"varint,2,opt,name=delivery_mode,json=deliveryMode,proto3,enum=event.v1.DeliveryMode" json:"delivery_mode,omitempty"`
	// Worker group name (only used with WORKER_POOL mode).
	WorkerGroup string `protobuf:"bytes,3,opt,name=worker_group,json=workerGroup,proto3" json:"worker_group,omitempty"`
	// Where to start reading messages.
	StartFrom StartPosition `protobuf:"varint,4,opt,name=start_from,json=startFrom,proto3,enum=event.v1.StartPosition" json:"start_from,omitempty"`
	// Start time (used with START_POSITION_TIMESTAMP).
	StartTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Filter out messages older than this duration.
	MaxAge *durationpb.Duration `protobuf:"bytes,6,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	// Only deliver the most recent message (sampling mode).
	LatestOnly bool `protobuf:"varint,7,opt,name=latest_only,json=latestOnly,proto3" json:"latest_only,omitempty"`
	// Message channel buffer size (0 = transport default).
	BufferSize int32 `protobuf:"varint,8,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	// Stable consumer identifier for checkpoint resume.
	ConsumerId    string `protobuf:"bytes,9,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_event_v1_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{8}
}

func (x *SubscribeRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *SubscribeRequest) GetDeliveryMode() DeliveryMode {
	if x != nil {
		return x.DeliveryMode
	}
	return DeliveryMode_DELIVERY_MODE_UNSPECIFIED
}

func (x *SubscribeRequest) GetWorkerGroup() string {
	if x != nil {
		return x.WorkerGroup
	}
	return ""
}

func (x *SubscribeRequest) GetStartFrom() StartPosition {
	if x != nil {
		return x.StartFrom
	}
	return StartPosition_START_POSITION_UNSPECIFIED
}

func (x *SubscribeRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *SubscribeRequest) GetMaxAge() *durationpb.Duration {
	if x != nil {
		return x.MaxAge
	}
	return nil
}

func (x *SubscribeRequest) GetLatestOnly() bool {
	if x != nil {
		return x.LatestOnly
	}
	return false
}

func (x *SubscribeRequest) GetBufferSize() int32 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

func (x *SubscribeRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

// Message is a streamed event message.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique message identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Source that published this message.
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// Message payload as bytes.
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Optional key-value metadata.
	Metadata map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// When the message was created.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Number of times this message has been retried.
	RetryCount int32 `protobuf:"varint,6,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	// Server-assigned ID for acknowledging this message.
	AckId         string `protobuf:"bytes,7,opt,name=ack_id,json=ackId,proto3" json:"ack_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_event_v1_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{9}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Message) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Message) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Message) GetAckId() string {
	if x != nil {
		return x.AckId
	}
	return ""
}

// AckEntry is a single acknowledgment entry.
type AckEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ack_id from the received Message.
	AckId string `protobuf:"bytes,1,opt,name=ack_id,json=ackId,proto3" json:"ack_id,omitempty"`
	// Empty string for success, non-empty for nack (triggers redelivery).
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckEntry) Reset() {
	*x = AckEntry{}
	mi := &file_event_v1_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckEntry) ProtoMessage() {}

func (x *AckEntry) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckEntry.ProtoReflect.Descriptor instead.
func (*AckEntry) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{10}
}

func (x *AckEntry) GetAckId() string {
	if x != nil {
		return x.AckId
	}
	return ""
}

func (x *AckEntry) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// AckRequest is the request for Ack.
type AckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One or more acknowledgment entries.
	Entries       []*AckEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_event_v1_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{11}
}

func (x *AckRequest) GetEntries() []*AckEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// AckResponse is the response for Ack.
type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_event_v1_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{12}
}

// HealthRequest is the request for Health.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_event_v1_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{13}
}

// HealthResponse is the response for Health.
type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=event.v1.HealthStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_event_v1_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_event_v1_event_proto_rawDescGZIP(), []int{14}
}

func (x *HealthResponse) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_event_v1_event_proto protoreflect.FileDescriptor

const file_event_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x14event/v1/event.proto\x12\bevent.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"*\n" +
	"\x14RegisterEventRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x17\n" +
	"\x15RegisterEventResponse\",\n" +
	"\x16UnregisterEventRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x19\n" +
	"\x17UnregisterEventResponse\"\x13\n" +
	"\x11ListEventsRequest\",\n" +
	"\x12ListEventsResponse\x12\x16\n" +
	"\x06events\x18\x01 \x03(\tR\x06events\"\xd1\x01\n" +
	"\x0ePublishRequest\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12B\n" +
	"\bmetadata\x18\x04 \x03(\v2&.event.v1.PublishRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"!\n" +
	"\x0fPublishResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x92\x03\n" +
	"\x10SubscribeRequest\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12;\n" +
	"\rdelivery_mode\x18\x02 \x01(\x0e2\x16.event.v1.DeliveryModeR\fdeliveryMode\x12!\n" +
	"\fworker_group\x18\x03 \x01(\tR\vworkerGroup\x126\n" +
	"\n" +
	"start_from\x18\x04 \x01(\x0e2\x17.event.v1.StartPositionR\tstartFrom\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x122\n" +
	"\amax_age\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x06maxAge\x12\x1f\n" +
	"\vlatest_only\x18\a \x01(\bR\n" +
	"latestOnly\x12\x1f\n" +
	"\vbuffer_size\x18\b \x01(\x05R\n" +
	"bufferSize\x12\x1f\n" +
	"\vconsumer_id\x18\t \x01(\tR\n" +
	"consumerId\"\xb7\x02\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12;\n" +
	"\bmetadata\x18\x04 \x03(\v2\x1f.event.v1.Message.MetadataEntryR\bmetadata\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vretry_count\x18\x06 \x01(\x05R\n" +
	"retryCount\x12\x15\n" +
	"\x06ack_id\x18\a \x01(\tR\x05ackId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\bAckEntry\x12\x15\n" +
	"\x06ack_id\x18\x01 \x01(\tR\x05ackId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\":\n" +
	"\n" +
	"AckRequest\x12,\n" +
	"\aentries\x18\x01 \x03(\v2\x12.event.v1.AckEntryR\aentries\"\r\n" +
	"\vAckResponse\"\x0f\n" +
	"\rHealthRequest\"\xd7\x01\n" +
	"\x0eHealthResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.event.v1.HealthStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12?\n" +
	"\adetails\x18\x03 \x03(\v2%.event.v1.HealthResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*i\n" +
	"\fDeliveryMode\x12\x1d\n" +
	"\x19DELIVERY_MODE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DELIVERY_MODE_BROADCAST\x10\x01\x12\x1d\n" +
	"\x19DELIVERY_MODE_WORKER_POOL\x10\x02*\x86\x01\n" +
	"\rStartPosition\x12\x1e\n" +
	"\x1aSTART_POSITION_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18START_POSITION_BEGINNING\x10\x01\x12\x19\n" +
	"\x15START_POSITION_LATEST\x10\x02\x12\x1c\n" +
	"\x18START_POSITION_TIMESTAMP\x10\x03*\x81\x01\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x02\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x032\x8a\x05\n" +
	"\fEventService\x12k\n" +
	"\rRegisterEvent\x12\x1e.event.v1.RegisterEventRequest\x1a\x1f.event.v1.RegisterEventResponse\"\x19\x82\xd3\xe4\x93\x02\x13\"\x11/v1/events/{name}\x12q\n" +
	"\x0fUnregisterEvent\x12 .event.v1.UnregisterEventRequest\x1a!.event.v1.UnregisterEventResponse\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/v1/events/{name}\x12[\n" +
	"\n" +
	"ListEvents\x12\x1b.event.v1.ListEventsRequest\x1a\x1c.event.v1.ListEventsResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/events\x12f\n" +
	"\aPublish\x12\x18.event.v1.PublishRequest\x1a\x19.event.v1.PublishResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/events/{event}/messages\x12<\n" +
	"\tSubscribe\x12\x1a.event.v1.SubscribeRequest\x1a\x11.event.v1.Message0\x01\x12F\n" +
	"\x03Ack\x12\x14.event.v1.AckRequest\x1a\x15.event.v1.AckResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/v1/ack\x12O\n" +
	"\x06Health\x12\x17.event.v1.HealthRequest\x1a\x18.event.v1.HealthResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/healthB9Z7github.com/rbaliyan/event-server/proto/event/v1;eventpbb\x06proto3"

var (
	file_event_v1_event_proto_rawDescOnce sync.Once
	file_event_v1_event_proto_rawDescData []byte
)

func file_event_v1_event_proto_rawDescGZIP() []byte {
	file_event_v1_event_proto_rawDescOnce.Do(func() {
		file_event_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_v1_event_proto_rawDesc), len(file_event_v1_event_proto_rawDesc)))
	})
	return file_event_v1_event_proto_rawDescData
}

var file_event_v1_event_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_event_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_event_v1_event_proto_goTypes = []any{
	(DeliveryMode)(0),               // 0: event.v1.DeliveryMode
	(StartPosition)(0),              // 1: event.v1.StartPosition
	(HealthStatus)(0),               // 2: event.v1.HealthStatus
	(*RegisterEventRequest)(nil),    // 3: event.v1.RegisterEventRequest
	(*RegisterEventResponse)(nil),   // 4: event.v1.RegisterEventResponse
	(*UnregisterEventRequest)(nil),  // 5: event.v1.UnregisterEventRequest
	(*UnregisterEventResponse)(nil), // 6: event.v1.UnregisterEventResponse
	(*ListEventsRequest)(nil),       // 7: event.v1.ListEventsRequest
	(*ListEventsResponse)(nil),      // 8: event.v1.ListEventsResponse
	(*PublishRequest)(nil),          // 9: event.v1.PublishRequest
	(*PublishResponse)(nil),         // 10: event.v1.PublishResponse
	(*SubscribeRequest)(nil),        // 11: event.v1.SubscribeRequest
	(*Message)(nil),                 // 12: event.v1.Message
	(*AckEntry)(nil),                // 13: event.v1.AckEntry
	(*AckRequest)(nil),              // 14: event.v1.AckRequest
	(*AckResponse)(nil),             // 15: event.v1.AckResponse
	(*HealthRequest)(nil),           // 16: event.v1.HealthRequest
	(*HealthResponse)(nil),          // 17: event.v1.HealthResponse
	nil,                             // 18: event.v1.PublishRequest.MetadataEntry
	nil,                             // 19: event.v1.Message.MetadataEntry
	nil,                             // 20: event.v1.HealthResponse.DetailsEntry
	(*timestamppb.Timestamp)(nil),   // 21: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),     // 22: google.protobuf.Duration
}
var file_event_v1_event_proto_depIdxs = []int32{
	18, // 0: event.v1.PublishRequest.metadata:type_name -> event.v1.PublishRequest.MetadataEntry
	0,  // 1: event.v1.SubscribeRequest.delivery_mode:type_name -> event.v1.DeliveryMode
	1,  // 2: event.v1.SubscribeRequest.start_from:type_name -> event.v1.StartPosition
	21, // 3: event.v1.SubscribeRequest.start_time:type_name -> google.protobuf.Timestamp
	22, // 4: event.v1.SubscribeRequest.max_age:type_name -> google.protobuf.Duration
	19, // 5: event.v1.Message.metadata:type_name -> event.v1.Message.MetadataEntry
	21, // 6: event.v1.Message.timestamp:type_name -> google.protobuf.Timestamp
	13, // 7: event.v1.AckRequest.entries:type_name -> event.v1.AckEntry
	2,  // 8: event.v1.HealthResponse.status:type_name -> event.v1.HealthStatus
	20, // 9: event.v1.HealthResponse.details:type_name -> event.v1.HealthResponse.DetailsEntry
	3,  // 10: event.v1.EventService.RegisterEvent:input_type -> event.v1.RegisterEventRequest
	5,  // 11: event.v1.EventService.UnregisterEvent:input_type -> event.v1.UnregisterEventRequest
	7,  // 12: event.v1.EventService.ListEvents:input_type -> event.v1.ListEventsRequest
	9,  // 13: event.v1.EventService.Publish:input_type -> event.v1.PublishRequest
	11, // 14: event.v1.EventService.Subscribe:input_type -> event.v1.SubscribeRequest
	14, // 15: event.v1.EventService.Ack:input_type -> event.v1.AckRequest
	16, // 16: event.v1.EventService.Health:input_type -> event.v1.HealthRequest
	4,  // 17: event.v1.EventService.RegisterEvent:output_type -> event.v1.RegisterEventResponse
	6,  // 18: event.v1.EventService.UnregisterEvent:output_type -> event.v1.UnregisterEventResponse
	8,  // 19: event.v1.EventService.ListEvents:output_type -> event.v1.ListEventsResponse
	10, // 20: event.v1.EventService.Publish:output_type -> event.v1.PublishResponse
	12, // 21: event.v1.EventService.Subscribe:output_type -> event.v1.Message
	15, // 22: event.v1.EventService.Ack:output_type -> event.v1.AckResponse
	17, // 23: event.v1.EventService.Health:output_type -> event.v1.HealthResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_event_v1_event_proto_init() }
func file_event_v1_event_proto_init() {
	if File_event_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_v1_event_proto_rawDesc), len(file_event_v1_event_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_v1_event_proto_goTypes,
		DependencyIndexes: file_event_v1_event_proto_depIdxs,
		EnumInfos:         file_event_v1_event_proto_enumTypes,
		MessageInfos:      file_event_v1_event_proto_msgTypes,
	}.Build()
	File_event_v1_event_proto = out.File
	file_event_v1_event_proto_goTypes = nil
	file_event_v1_event_proto_depIdxs = nil
}
